name: Measure coverage

on:
  pull_request:
    branches:
      - develop
      - master
      - main
      - release
      - feature/*
  push:
    branches:
      - developer
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew jacocoDebugReport

      - name: Upload Report
        uses: 'actions/upload-artifact@v4'
        with:
          name: report.xml
          path: ${{ github.workspace }}/build/reports/jacoco/jacocoDebugReport/jacocoDebugReport.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoDebugReport/jacocoDebugReport.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          debug-mode: false
          title: Code Coverage
          update-comment: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')